### ISSUE TITLE
Check_policy needs to be turned off

### ISSUE THREAD

**Issue by lordbink** [strdco/ag-sync#1]
Check policy needs to be turned off for passwords to be synced. This can easily be added with the CHECK_POLICY=OFF in the first CASE. But in order for Check_policy to be turned back on you have to rerun the procedure.

Is there a way to automatically switch CHECK_POLICY back on within the script?

**Comment by dhmacher** [comment]
Thanks, I'll look into it when time allows!

**Comment by lordbink** [comment]
So, I don't know if this is an ideal solution, but it will work well for us. I added some duplicate code to change back CHECK_POLICY to ON when a password change is needed. So it will look like this:

```
INSERT INTO @queue ([sql])
SELECT N'
	ALTER LOGIN ['+sp.[name]+'] WITH '+
		SUBSTRING(
		(CASE WHEN x.is_policy_checked=1
		      THEN ', CHECK_POLICY=ON'
			  ELSE N'' END), 3, 10000)+N';'
FROM @primaryLogins AS x
INNER JOIN master.sys.server_principals AS sp ON x.[sid]=sp.[sid]
LEFT JOIN master.sys.sql_logins AS l ON sp.[sid]=l.[sid]
WHERE x.password_hash!=l.password_hash
```

And of course the previous addition of adding CHECK_POLICY=OFF to the first case:
```
		(CASE WHEN x.password_hash!=l.password_hash
		      THEN N', PASSWORD=0x'+CONVERT(nvarchar(max), x.password_hash, 2)+N' HASHED, CHECK_POLICY=OFF'
			  ELSE N'' END)+
```

I included these changes here: https://github.com/lordbink/ag-sync/commit/3ab6256a4e90d2990a0c15879b1e7d721571f4ef

In spite of this being usable in our environment I am not comfortable suggesting this solution. Let me know if you think of any downsides to this.
