### ISSUE TITLE
Script fails when attempts to replicate internal system use logins

### ISSUE THREAD

**Issue by alkarp** [strdco/ag-sync#3]
Script fails with the following error when it attempts to replicate internal system use logins:
> Msg 15025, Level 16, State 1, Line 8
> The server principal '##MS_PolicyEventProcessingLogin##' already exists.

More details about the "Certificate-based SQL Server Logins" logins: https://docs.microsoft.com/en-us/sql/relational-databases/security/authentication-access/principals-database-engine?redirectedfrom=MSDN&view=sql-server-ver15#certificate-based-sql-server-logins

Would be great to have an ability to exclude logins based on a name mask or at least exclude any ##*## logins.

**Comment by systobe** [comment]
I had the same issue.
Just add the following line between 102 and 103:
`UPPER(sp.[name]) NOT LIKE ''##MS%'' AND`
and this one between 182 and 183:
`sp.[name] NOT LIKE ('##MS_%') AND`
Of course you can change the filter e.g. like `##%##` instead of `##MS_%`

**Comment by dhmacher** [comment]
Added a filter to exclude ##%## logins. Thanks!
