### ISSUE TITLE
Can you add an exclusion list?

### ISSUE THREAD

**Issue by rfaulkner99** [strdco/ag-sync#4]
Sorry to ask for something that seems simple, but I am new to SQL programming. Could you add an exclusion list variable/array to exclude users that I do not want to replicate to the secondary replica? I am using Availability Groups, but not all of the DBs in our PROD environment are being replicated to our DR environment so I would like to exclude the logins that are not needed in DR. I would like this exclusion to exclude the login completely, including the permissions and DB mappings checks.

Thanks.

**Comment by dhmacher** [comment]
Added parameter @exclude_logins, which allows you to exclude specific logins (not wildcards, but a comma-separated list).

Example:
    @exclude_logins='DOMAIN\abc,DOMAIN\def,xyz'
